pre-commit:
  parallel: true
  jobs:
    - run: cargo clippy
    - run: cargo fmt
    - run: echo 'Hello'; echo 'STDERR' >&2; exit 1
    - run: echo {staged_files}
    - run: echo {staged_files}
    - run: echo {staged_files}
    - run: sleep 5
    - run: sleep 5
    - run: echo {push_files}

test:
  jobs:
    - run: echo test
