[package]
name = "righthook"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
colored = "3.0.0"
eyre = "0.6.12"
git2 = "0.20.1"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
